# Generated by Django 4.2 on 2023-04-11 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=30, null=True)),
                ("Email", models.CharField(blank=True, max_length=30, null=True)),
                ("Phone", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Base_device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Model_device",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("Brand", models.CharField(blank=True, max_length=20, null=True)),
                ("ScreenSize", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cpu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=30, null=True)),
                ("Core", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "base_device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api2.base_device",
                    ),
                ),
                ("Battery", models.IntegerField(blank=True, null=True)),
            ],
            bases=("api2.base_device",),
        ),
        migrations.CreateModel(
            name="Tablet",
            fields=[
                (
                    "base_device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api2.base_device",
                    ),
                ),
            ],
            bases=("api2.base_device",),
        ),
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "base_device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api2.base_device",
                    ),
                ),
                ("Ram", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "Cpu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api2.cpu"
                    ),
                ),
            ],
            bases=("api2.base_device",),
        ),
    ]
