# Generated by Django 4.2 on 2023-04-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Text", models.TextField(blank=True, default="", null=True)),
                ("Code", models.TextField(blank=True, default="", null=True)),
                ("Option1", models.CharField(blank=True, max_length=255, null=True)),
                ("Option2", models.CharField(blank=True, max_length=255, null=True)),
                ("Option3", models.CharField(blank=True, max_length=255, null=True)),
                ("Option4", models.CharField(blank=True, max_length=255, null=True)),
                ("Answer", models.IntegerField(blank=True, null=True)),
                ("Level", models.IntegerField(blank=True, null=True)),
                ("Time", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StuCode", models.CharField(blank=True, max_length=255, null=True)),
                ("Token", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "State",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("در حال پاسخگویی", "in"),
                            ("اتمام سوالات", "end"),
                            ("در انتظار شروع", "wait"),
                            ("حذف شده", "delete"),
                        ],
                        default="در انتظار شروع",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("Index", models.IntegerField(blank=True, default=0, null=True)),
                ("FalseCounter", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "TimeStampQuestion",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
        ),
    ]
