# Generated by Django 4.2 on 2023-04-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="StuCode",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
