# Generated by Django 4.2 on 2023-04-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_stucode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="Round",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="TimeStampQuestion",
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
